- src/main/scala/com/gu/CheckPriceRisePostConditions.scala
- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
- src/main/scala/com/gu/Config.scala
- src/main/scala/com/gu/CurrentGuardianWeeklySubscription.scala
- src/main/scala/com/gu/NewGuardianWeeklySubscription.scala
- src/main/scala/com/gu/RemoveRatePlans.scala
- src/main/scala/com/gu/ZuoraClient.scala
* `Cancellation Save Discount` product rate plan does not have price, so we need to make it `Option`
*  `RemoveRatePlans` should filter on `productRatePlanId`, NOT `ratePlanId`
* `ThereDoesNotExistAFutureAmendmentOnThePriceRiseDate` should take into account holidays and retention discounts
> Fix do not remove retention discounts and holidays

- README.md
- src/main/scala/com/gu/DryRunner.scala
```
/**
* Check pre-conditions for all import records, and outputs stats on failed conditions.
* Do not write to Zuora.
*/
object DryRunner extends App with LazyLogging
```
Example dry run:
```
Multiple main classes detected, select one to run:
[1] com.gu.DryRunner
[2] com.gu.Main
[info] Packaging /Users/mgalic/sandbox/zuora-price-riser/target/scala-2.12/zuora-price-riser_2.12-0.1.0-SNAPSHOT.jar ...
Enter number: [info] Done packaging.
1
[info] Running com.gu.DryRunner subs.csv
2018-12-19 19:00:43,518 [INFO] - Start dry run processing subs.csv...
2018-12-19 19:00:45,993 [INFO] - Dry run completed for subs.csv
2018-12-19 19:00:45,993 [INFO] - --------------------------------------------------------------
2018-12-19 19:00:45,993 [INFO] - Results (count):
2018-12-19 19:00:45,993 [INFO] - …
```
> Add dry run

- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
- src/main/scala/com/gu/FileImporter.scala
Depend on current Zuora subscription (without discounts) on calculating the price rise cap.
> Do not trust current price from import file

- src/main/scala/com/gu/Config.scala
Import data contains records not satisfying 33% cap.
Note, this is a separate issue from 33% cap not satisfied due to subscription having discounts.
> Increase price rise cap to 99%

- src/main/scala/com/gu/Country.scala
- src/main/scala/com/gu/NewGuardianWeeklySubscription.scala
- src/test/scala/com/gu/NewGuardianWeeklySubscriptionSpec.scala
If a subscriber uses a non-standard currency for a delivery country (e.g. paying in GBP whilst having magazines delivered to Germany), then they should be on the Rest of World plan.
> Fix plan selection for subscribers who pay in a non-standard currency

- src/main/scala/com/gu/DryRunner.scala
- src/main/scala/com/gu/Main.scala
- src/main/scala/com/gu/ZuoraClient.scala
Optimise script - no need to get the new product catalogue for each import record.
> Execute getNewGuardianWeeklyProductCatalogue only once

- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
- src/main/scala/com/gu/Config.scala
- src/main/scala/com/gu/CurrentGuardianWeeklySubscription.scala
Make it distinction between new and old Zuora IDs clearer.
```
"2c92c0f86716796f016717d9e1465e03", // "name":"GW Nov 19 - Quarterly - Domestic"	
"2c92c0f965d280590165f16b1b9946c2", // "name":"GW Oct 18 - Annual - Domestic"	
"2c92c0f965dc30640165f150c0956859", // "name":"GW Oct 18 - Quarterly - Domestic"	
"2c92c0f965f2122101660fb33ed24a45", // "name":"GW Oct 18 - Annual - ROW"	
"2c92c0f965f2122101660fb81b745a06", // "name":"GW Oct 18 - Quarterly - ROW"
```
were actually new IDs (DEV) so should not have been in `guardianWeeklyProductRatePlanIds`
> Collect old pre-price rise IDs in separate object

- src/main/scala/com/gu/Config.scala
- src/main/scala/com/gu/Country.scala
- src/main/scala/com/gu/NewGuardianWeeklySubscription.scala
- src/main/scala/com/gu/ZuoraClient.scala
* Constrain the concept of `NewGuardianWeeklyProduct` to mean
- new product (after price rise)
- Guardian weekly
- annual or quarterly
* Separate new IDs in their own object 
* FIXME: Once we enable all currencies we could hardcode the new GW product catalogue
> Check NewGuardianWeeklyProduct against hardcoded new productRatePlanIds

- src/main/scala/com/gu/NewGuardianWeeklySubscription.scala
- src/test/scala/com/gu/NewGuardianWeeklyProductSpec.scala
If the currency is not activated in Zuora product catalogue then the script would fail.
> Add currency exists check

- src/main/scala/com/gu/CheckPriceRisePostConditions.scala
- src/main/scala/com/gu/NewGuardianWeeklySubscription.scala
- src/main/scala/com/gu/ZuoraClient.scala
`priceChangeOption` 
> Applies an automatic price change when a termed subscription is renewed.
We set it to `NoChange`, that is, the price should not change on subsequent renewals after the price rise.
> Add PriceShouldNotChangeOnSubsequentRenewals post condition

- src/main/scala/com/gu/BillingPreview.scala
- src/main/scala/com/gu/CheckPriceRisePostConditions.scala
- src/main/scala/com/gu/Main.scala
- src/main/scala/com/gu/ZuoraClient.scala
- src/test/scala/com/gu/BillingPreviewSpec.scala
- src/test/scala/com/gu/NewGuardianWeeklySubscriptionSpec.scala
Zuora REST API has limited ability feature which allows for invoice preview:
https://www.zuora.com/developer/api-reference/#operation/POST_BillingPreview
We use this to check the invoice charge amount at the price rise date.
Note we have to manually add the tax as the endpoint currently does not account for tax.
> Add BillingPreview postcondition

- src/main/scala/com/gu/Main.scala
- src/main/scala/com/gu/ZuoraClient.scala
Otherwise this check fails if the user has a holiday credit on their account.
We also now check that there is only a single item (charge) in the list of invoice items, in order to protect against the case where we are accidentally charging users for multiple products at once.
> Exclude discounts from post-price-rise invoice amount checks

- src/main/scala/com/gu/RemoveRatePlans.scala
- src/main/scala/com/gu/ZuoraClient.scala
When processing a price rise, all old rate plans were being removed from a subscription. Bizarrely, Zuora will allow you to re-remove a rate plan which has already been removed by a prior operation (e.g. a manual renewal of a one-off plan), creating a new amendment as a side-effect, that is, removal of the same rate plan is NOT idempotent. According to [this clause](https://github.com/guardian/fulfilment-lambdas/blob/master/src/weekly/query.js#L60-L61) in the fulfilment query, any old Guardian Weekly rate plan which was re-removed became eligible for fulfilment again between the time of price rise script execution and the user’s price rise date.
> Do not remove old Guardian Weekly rate plans

- src/main/scala/com/gu/Main.scala
- src/main/scala/com/gu/ResumeProcessing.scala
For example,
```
run Price_Rise_Official_Notice_31Dec.csv 358675
```
should resume processing from subscription name 358675 in price rise import file.
> Add resume processing from subscription name

- src/main/scala/com/gu/BillRunVerifier.scala
- src/main/scala/com/gu/ZuoraClient.scala
Retry [Billing Preview call](https://www.zuora.com/developer/api-reference/#operation/POST_BillingPreview) as it keeps failing due to `optimistic locking failed`:
```
{
"success": false,
"processId": "3234C1527FB1625A",
"reasons": [{
"code": 59870050,
"message": "Object of class [com.zuora.zbilling.subscription.model.Subscription] with identifier [2c92a00768a2b3890168a35e2ded3e28]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [com.zuora.zbilling.subscription.model.Subscription#2c92a00768a2b3890168a35e2ded3e28]"
}]
}
```
> Retry billing preview on optimistic locking failed

- src/main/scala/com/gu/AtLeastOneYearPassed.scala
- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
- src/test/scala/com/gu/AtLeastOneYearPassedSpec.scala
Add precondition where at least one year passed between current subscription `customerAcceptanceDate` and price rise date.
> Price rise only after one year

- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
- src/main/scala/com/gu/PriceRiseFallsOnAcceptableDay.scala
- src/test/scala/com/gu/PriceRiseFallsOnAcceptableDaySpec.scala
Now that we are processing all price rises for the rest of the year (as opposed to a week by week batch of price rises), we need to cope with cases where price rise date != next invoice date.
> Handle price rises scheduled for up to one year in the future

- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
- src/main/scala/com/gu/DryRunner.scala
- src/main/scala/com/gu/Main.scala
- src/main/scala/com/gu/PriceRiseFallsOnAcceptableDay.scala
- src/main/scala/com/gu/ZuoraClient.scala
- src/test/scala/com/gu/PriceRiseFallsOnAcceptableDaySpec.scala
The approach I tried in https://github.com/guardian/zuora-price-riser/pull/43 would not work in all scenarios.
For example, consider a user who signed up for a quarterly plan on `2018-01-31` and is due for a price rise on `2019-07-31`. Zuora will always charge this user on the last day of the month. If the current next invoice date is `2019-04-30` the old logic considered `2019-07-30`  (and not `2019-07-31`) to be a valid price rise date.
The new approach relies on Zuora's billing preview functionality instead of attempting to manage this logic ourselves.
Whilst making this change I also noticed that the post-checks would fail since they were expecting a single invoice to be returned by the billing preview. This expectation is invalid now that some price rises will not take place for …
> Handle price rises scheduled for one year in the future attempt 2

- src/main/scala/com/gu/FileImporter.scala
Some manual fixes to the data are required. This means that the 'date_letter_sent' column from the input file is not going to be 100% accurate.
We do not need this date and nor does Izabela. This date is only used by Salesforce for CSR display, and it is just a calculation of 56 days before the price rise date. 
Consequently the simplest solution is to make date letter sent a formula field in Salesforce, or add a new column to the CSV (which calculate this) before uploading to Salesforce. It will be omitted from the DL table altogether.
> Remove date letter sent from output row

- src/main/scala/com/gu/DryRunner.scala
- src/main/scala/com/gu/ExtendTermRequestBuilder.scala
- src/main/scala/com/gu/Main.scala
- src/test/scala/com/gu/ExtendTermRequestBuilderSpec.scala
Since we now accept price rise dates which are after the next invoice date, we need to tweak the term extension logic accordingly.
> Allow term extension logic to cope with cases where price rise date is later than next invoice date

- src/main/scala/com/gu/CheckPriceRisePreConditions.scala
There are some rows in the full file which indicate that a price rise should have _already_ been applied. 
If we've already sent a letter and applied the price rise this is not a problem - the script will just [skip](https://github.com/guardian/zuora-price-riser/blob/master/src/main/scala/com/gu/Main.scala#L48-L53) over the row. 
Although _skipping_ is acceptable, we should not be _applying_ a price rise to any subscription with a price rise date before `2019-05-12` as part of the full run. 
This is technically possible, but is likely to indicate that the subscription was missed when the letters for that price rise period were sent. Therefore it's safer to refuse to process the price rise altogether in such cases.
_N.B. The next set of letters will target users with a price rise date …
> Add safety check to ensure that nobody gets a price rise without receiving a letter
